language: node_js
node_js:
  - 10

before_install:
  - npm i coveralls

script:
  - npm run lint
  - npm run test:ci

notifications:
  email:
    recipients:
      - roccocataldo@gmail.com
    on_success: always
    on_failure: always
